application: bubblecatch
version: 1
runtime: python27
api_version: 1
threadsafe: true




handlers:
- url: /
  static_files: BubbleCatch.html
  upload: BubbleCatch.html

- url: /.*
  static_files: BubbleGenerator.js
  upload: BubbleGenerator.js